version: '3.8'

services:
  # --- Database PostgreSQL (Lokal di CentOS) ---
  db-postgres:
    image: postgres:15-alpine
    container_name: hms-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hexing@2026
      POSTGRES_DB: hexing_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  # --- HMS Application ---
  hms-app:
    build: .
    container_name: hms-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db-postgres
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production

volumes:
  postgres_data: